name: CI When PR

on:
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    # Gradle 설정
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    # Gradle 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # Gradle Testing
    - name: Test with Gradle
      run: ./gradlew --info test
      
    # 테스트 결과 PR에 내용 작성
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: build/test-results/**/*.xml
